project_id = "casbhtutijxqcymsimub"

[functions.create-priority-checkout]
verify_jwt = false

[functions.waitlist-signup]
verify_jwt = false

[functions.send-priority-welcome-email]
verify_jwt = false
